### ISSUE TITLE
Does not build on contextify 0.1.15

### ISSUE THREAD

**Issue by alexkrohn** [jaredgk/IMgui#1]
Hi there, 

I'm not sure if this is an error on node, contextify or the IMgui side. I got this error while trying to run npm install in the IMgui directory. Any suggestions?

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.

I updated node and npm, but to no avail. 

[Here is the log file as well.](https://drive.google.com/file/d/0Bzf4PHnJazVfUlYzRng5U2YwLVU/view?usp=sharing). Thanks!

-Alex

**Comment by jaredgk** [comment]
Hey Alex,
I think you may be using one of the older versions of the code. The most
up-to-date packages are in the "IMgui-electron-packages" repo, and since
they use Electron they do not require any npm commands (although there is a
shell script required to compile the IMa executable).

Link: https://github.com/jaredgk/IMgui-electron-packages

Let me know if that wasn't the issue, or if there's anything else that
comes up.

-Jared

**Comment by alexkrohn** [comment]
Hi Jared,

Thanks for your explanation! You are right. The version linked from the Hey
lab's website was for an older version. Thanks for clearing this up! It may
be worth sending an email to Jodi to tell her to update her website as
well.

Link to where I found IMgui:
https://bio.cst.temple.edu/~hey/software/software.htm#IMGui

Thanks again!

-Alex

**Comment by jaredgk** [comment]
Good to hear it's working, and thanks for the heads up about the link!
-Jared
